<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>11-promises-demo2</title>
</head>
<body>
    <script>
    //wrap an asynchronous operation in a promise
new Promise((resolve, reject) => {
    console.log('initial');
    resolve();
})
    .then(() => {
        throw new Error('Something failed');
        console.log('Do this');
    })
    //It's possible to chain after a failure, i.e. a catch,
    //which is useful to accomplish new actions even after an action failed in the chain.
    .catch(() => {
        console.log('Do that');
    })
    .then(() => {
        console.log('Do this whatever happened before');
    });
</script>
</body>
</html>
